/**
 * A country outline pre-projected into the shared SVG viewBox.
 * Generated by `npm run geo:build` — see scripts/build-geo-data.mjs.
 */
export interface CountryShape {
  /** Numeric ISO 3166-1 code, zero-padded to 3 digits (e.g. "156" for China). */
  id: string;
  /** English name as shipped by world-atlas. */
  name: string;
  /** SVG path data in viewBox coordinates. */
  d: string;
  /** Label anchor, viewBox coordinates. */
  cx: number;
  cy: number;
}

/** A country ready to render: outline + localised name + directory counts. */
export interface MapCountry extends CountryShape {
  /** ISO 3166-1 alpha-2, e.g. "CN". Empty when the join failed. */
  iso2: string;
  /** Localised display name. */
  label: string;
  /** Stations the directory lists for this country. */
  stationCount: number;
}

/**
 * Compact station payload for map markers.
 * Coordinates are already projected into the map viewBox on the server, so the
 * client needs no geo library at all.
 */
export interface StationMarker {
  uuid: string;
  name: string;
  country: string;
  countrycode: string;
  /** viewBox x. */
  x: number;
  /** viewBox y. */
  y: number;
  /** Pre-resolved stream URL. */
  stream: string;
  hls: number;
  codec: string;
  bitrate: number;
  tags: string;
}
